services:
  - type: web
    name: secure-exam-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn examapp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: examapp.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: ALLOWED_HOSTS
        value: secure-exam-app.onrender.com
