# Generated by Django 4.2.7 on 2023-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='que',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
