# Generated by Django 4.2.7 on 2023-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0004_alter_question_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='que',
            field=models.TextField(),
        ),
    ]
